language: php

php:
  - 7.2
  - 7.3

mysql:
  database: dbtest
  username: root
  encoding: utf8

install:
  - curl -o config/cacert.pem https://curl.haxx.se/ca/cacert.pem
  - travis_retry composer install --no-interaction --prefer-source
  - mysql -e 'create database dbtest;'

script: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover clover.xml

after_success: bash <(curl -s https://codecov.io/bash)
